/* tslint:disable */
/* eslint-disable */
/**
 * Person Management API
 * API для управления объектами Person. Backend на Jakarta EE + JPA (EclipseLink).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';


export const Color = {
    Red: 'RED',
    Black: 'BLACK',
    Blue: 'BLUE',
    White: 'WHITE',
    Brown: 'BROWN'
} as const;

export type Color = typeof Color[keyof typeof Color];


export interface CoordinatesRequest {
    'x': number;
    'y': number;
}
export interface CoordinatesResponse {
    'id'?: number;
    'x': number;
    'y': number;
}

export const Country = {
    Russia: 'RUSSIA',
    UnitedKingdom: 'UNITED_KINGDOM',
    Spain: 'SPAIN',
    Italy: 'ITALY',
    SouthKorea: 'SOUTH_KOREA'
} as const;

export type Country = typeof Country[keyof typeof Country];


export interface FilterField {
    'field'?: string;
    'pattern'?: string;
}
export interface IdBase {
    'id'?: number;
}
export interface LocationRequest {
    'x': number;
    'y': number;
    'z': number;
}
export interface LocationResponse {
    'id'?: number;
    'x': number;
    'y': number;
    'z': number;
}
export interface PageCoordinates {
    'content'?: Array<CoordinatesResponse>;
    'totalElements'?: number;
    'totalPages'?: number;
}
export interface PageLocation {
    'content'?: Array<LocationResponse>;
    'totalElements'?: number;
    'totalPages'?: number;
}
export interface PagePerson {
    'content'?: Array<PersonResponse>;
    'totalElements'?: number;
    'totalPages'?: number;
}
export interface PersonRequest {
    'name': string;
    'coordinatesId': number;
    'eyeColor': Color;
    'hairColor': Color;
    'locationId'?: number;
    'height'?: number | null;
    'nationality'?: Country;
}


export interface PersonResponse {
    'id'?: number;
    'name': string;
    'coordinatesId': number;
    'eyeColor': Color;
    'hairColor': Color;
    'locationId'?: number;
    'height'?: number | null;
    'nationality'?: Country;
    'creationDate': string;
}


export interface SearchRequest {
    'page'?: number;
    'size'?: number;
    'sort'?: Array<SortField>;
    'filters'?: Array<FilterField>;
}

export const SortDirection = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;

export type SortDirection = typeof SortDirection[keyof typeof SortDirection];


export interface SortField {
    'field'?: string;
    'direction'?: SortDirection;
}



/**
 * CoordinatesApi - axios parameter creator
 */
export const CoordinatesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CoordinatesRequest} coordinatesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCoordinates: async (coordinatesRequest: CoordinatesRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('createCoordinates', 'coordinatesRequest', coordinatesRequest)
            const localVarPath = `/coordinates`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(coordinatesRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCoordinates: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('deleteCoordinates', 'id', id)
            const localVarPath = `/coordinates/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCoordinatesById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('getCoordinatesById', 'id', id)
            const localVarPath = `/coordinates/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary поиск и фильтрация Coordinates
         * @param {SearchRequest} searchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchCoordinates: async (searchRequest: SearchRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('searchCoordinates', 'searchRequest', searchRequest)
            const localVarPath = `/coordinates/search`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {CoordinatesRequest} coordinatesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCoordinates: async (id: number, coordinatesRequest: CoordinatesRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('updateCoordinates', 'id', id)
            assertParamExists('updateCoordinates', 'coordinatesRequest', coordinatesRequest)
            const localVarPath = `/coordinates/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(coordinatesRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CoordinatesApi - functional programming interface
 */
export const CoordinatesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CoordinatesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CoordinatesRequest} coordinatesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCoordinates(coordinatesRequest: CoordinatesRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CoordinatesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCoordinates(coordinatesRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoordinatesApi.createCoordinates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCoordinates(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCoordinates(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoordinatesApi.deleteCoordinates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCoordinatesById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CoordinatesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCoordinatesById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoordinatesApi.getCoordinatesById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary поиск и фильтрация Coordinates
         * @param {SearchRequest} searchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchCoordinates(searchRequest: SearchRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageCoordinates>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchCoordinates(searchRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoordinatesApi.searchCoordinates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {CoordinatesRequest} coordinatesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCoordinates(id: number, coordinatesRequest: CoordinatesRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CoordinatesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCoordinates(id, coordinatesRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoordinatesApi.updateCoordinates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CoordinatesApi - factory interface
 */
export const CoordinatesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CoordinatesApiFp(configuration)
    return {
        /**
         * 
         * @param {CoordinatesRequest} coordinatesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCoordinates(coordinatesRequest: CoordinatesRequest, options?: RawAxiosRequestConfig): AxiosPromise<CoordinatesResponse> {
            return localVarFp.createCoordinates(coordinatesRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCoordinates(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteCoordinates(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCoordinatesById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<CoordinatesResponse> {
            return localVarFp.getCoordinatesById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary поиск и фильтрация Coordinates
         * @param {SearchRequest} searchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchCoordinates(searchRequest: SearchRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageCoordinates> {
            return localVarFp.searchCoordinates(searchRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {CoordinatesRequest} coordinatesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCoordinates(id: number, coordinatesRequest: CoordinatesRequest, options?: RawAxiosRequestConfig): AxiosPromise<CoordinatesResponse> {
            return localVarFp.updateCoordinates(id, coordinatesRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CoordinatesApi - object-oriented interface
 */
export class CoordinatesApi extends BaseAPI {
    /**
     * 
     * @param {CoordinatesRequest} coordinatesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createCoordinates(coordinatesRequest: CoordinatesRequest, options?: RawAxiosRequestConfig) {
        return CoordinatesApiFp(this.configuration).createCoordinates(coordinatesRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id идентификатор ресурса
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteCoordinates(id: number, options?: RawAxiosRequestConfig) {
        return CoordinatesApiFp(this.configuration).deleteCoordinates(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id идентификатор ресурса
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCoordinatesById(id: number, options?: RawAxiosRequestConfig) {
        return CoordinatesApiFp(this.configuration).getCoordinatesById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary поиск и фильтрация Coordinates
     * @param {SearchRequest} searchRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchCoordinates(searchRequest: SearchRequest, options?: RawAxiosRequestConfig) {
        return CoordinatesApiFp(this.configuration).searchCoordinates(searchRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id идентификатор ресурса
     * @param {CoordinatesRequest} coordinatesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateCoordinates(id: number, coordinatesRequest: CoordinatesRequest, options?: RawAxiosRequestConfig) {
        return CoordinatesApiFp(this.configuration).updateCoordinates(id, coordinatesRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * LocationsApi - axios parameter creator
 */
export const LocationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary создать новую Location
         * @param {LocationRequest} locationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createLocation: async (locationRequest: LocationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('createLocation', 'locationRequest', locationRequest)
            const localVarPath = `/locations`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(locationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLocation: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('deleteLocation', 'id', id)
            const localVarPath = `/locations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLocationById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('getLocationById', 'id', id)
            const localVarPath = `/locations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary поиск и фильтрация Location
         * @param {SearchRequest} searchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchLocations: async (searchRequest: SearchRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('searchLocations', 'searchRequest', searchRequest)
            const localVarPath = `/locations/search`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {LocationRequest} locationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLocation: async (id: number, locationRequest: LocationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('updateLocation', 'id', id)
            assertParamExists('updateLocation', 'locationRequest', locationRequest)
            const localVarPath = `/locations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(locationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LocationsApi - functional programming interface
 */
export const LocationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LocationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary создать новую Location
         * @param {LocationRequest} locationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createLocation(locationRequest: LocationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LocationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createLocation(locationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationsApi.createLocation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteLocation(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteLocation(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationsApi.deleteLocation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLocationById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LocationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLocationById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationsApi.getLocationById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary поиск и фильтрация Location
         * @param {SearchRequest} searchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchLocations(searchRequest: SearchRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageLocation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchLocations(searchRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationsApi.searchLocations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {LocationRequest} locationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateLocation(id: number, locationRequest: LocationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LocationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateLocation(id, locationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationsApi.updateLocation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LocationsApi - factory interface
 */
export const LocationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LocationsApiFp(configuration)
    return {
        /**
         * 
         * @summary создать новую Location
         * @param {LocationRequest} locationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createLocation(locationRequest: LocationRequest, options?: RawAxiosRequestConfig): AxiosPromise<LocationResponse> {
            return localVarFp.createLocation(locationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLocation(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteLocation(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLocationById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<LocationResponse> {
            return localVarFp.getLocationById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary поиск и фильтрация Location
         * @param {SearchRequest} searchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchLocations(searchRequest: SearchRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageLocation> {
            return localVarFp.searchLocations(searchRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id идентификатор ресурса
         * @param {LocationRequest} locationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLocation(id: number, locationRequest: LocationRequest, options?: RawAxiosRequestConfig): AxiosPromise<LocationResponse> {
            return localVarFp.updateLocation(id, locationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LocationsApi - object-oriented interface
 */
export class LocationsApi extends BaseAPI {
    /**
     * 
     * @summary создать новую Location
     * @param {LocationRequest} locationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createLocation(locationRequest: LocationRequest, options?: RawAxiosRequestConfig) {
        return LocationsApiFp(this.configuration).createLocation(locationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id идентификатор ресурса
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteLocation(id: number, options?: RawAxiosRequestConfig) {
        return LocationsApiFp(this.configuration).deleteLocation(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id идентификатор ресурса
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLocationById(id: number, options?: RawAxiosRequestConfig) {
        return LocationsApiFp(this.configuration).getLocationById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary поиск и фильтрация Location
     * @param {SearchRequest} searchRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchLocations(searchRequest: SearchRequest, options?: RawAxiosRequestConfig) {
        return LocationsApiFp(this.configuration).searchLocations(searchRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id идентификатор ресурса
     * @param {LocationRequest} locationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateLocation(id: number, locationRequest: LocationRequest, options?: RawAxiosRequestConfig) {
        return LocationsApiFp(this.configuration).updateLocation(id, locationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * OperationsApi - axios parameter creator
 */
export const OperationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary вывести количество людей с заданным цветом волос в пределах указанной локации
         * @param {Color} hairColor 
         * @param {number} locationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countByHairColorAndLocation: async (hairColor: Color, locationId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('countByHairColorAndLocation', 'hairColor', hairColor)
            assertParamExists('countByHairColorAndLocation', 'locationId', locationId)
            const localVarPath = `/operations/countByHairColorAndLocation`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (hairColor !== undefined) {
                localVarQueryParameter['hairColor'] = hairColor;
            }

            if (locationId !== undefined) {
                localVarQueryParameter['locationId'] = locationId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary вернуть количество Person с заданным height
         * @param {number} height 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countByHeight: async (height: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('countByHeight', 'height', height)
            const localVarPath = `/operations/countByHeight`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (height !== undefined) {
                localVarQueryParameter['height'] = height;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary удалить один объект с заданной национальностью
         * @param {Country} nationality 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteByNationality: async (nationality: Country, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('deleteByNationality', 'nationality', nationality)
            const localVarPath = `/operations/deleteByNationality`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (nationality !== undefined) {
                localVarQueryParameter['nationality'] = nationality;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary вывести долю людей с заданным цветом глаз в процентах
         * @param {Color} eyeColor 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eyeColorShare: async (eyeColor: Color, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('eyeColorShare', 'eyeColor', eyeColor)
            const localVarPath = `/operations/eyeColorShare`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (eyeColor !== undefined) {
                localVarQueryParameter['eyeColor'] = eyeColor;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary рассчитать сумму значений height для всех Person
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sumHeight: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/operations/sumHeight`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OperationsApi - functional programming interface
 */
export const OperationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OperationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary вывести количество людей с заданным цветом волос в пределах указанной локации
         * @param {Color} hairColor 
         * @param {number} locationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async countByHairColorAndLocation(hairColor: Color, locationId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.countByHairColorAndLocation(hairColor, locationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OperationsApi.countByHairColorAndLocation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary вернуть количество Person с заданным height
         * @param {number} height 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async countByHeight(height: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.countByHeight(height, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OperationsApi.countByHeight']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary удалить один объект с заданной национальностью
         * @param {Country} nationality 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteByNationality(nationality: Country, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteByNationality(nationality, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OperationsApi.deleteByNationality']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary вывести долю людей с заданным цветом глаз в процентах
         * @param {Color} eyeColor 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async eyeColorShare(eyeColor: Color, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.eyeColorShare(eyeColor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OperationsApi.eyeColorShare']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary рассчитать сумму значений height для всех Person
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sumHeight(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sumHeight(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OperationsApi.sumHeight']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OperationsApi - factory interface
 */
export const OperationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OperationsApiFp(configuration)
    return {
        /**
         * 
         * @summary вывести количество людей с заданным цветом волос в пределах указанной локации
         * @param {Color} hairColor 
         * @param {number} locationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countByHairColorAndLocation(hairColor: Color, locationId: number, options?: RawAxiosRequestConfig): AxiosPromise<number> {
            return localVarFp.countByHairColorAndLocation(hairColor, locationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary вернуть количество Person с заданным height
         * @param {number} height 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countByHeight(height: number, options?: RawAxiosRequestConfig): AxiosPromise<number> {
            return localVarFp.countByHeight(height, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary удалить один объект с заданной национальностью
         * @param {Country} nationality 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteByNationality(nationality: Country, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteByNationality(nationality, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary вывести долю людей с заданным цветом глаз в процентах
         * @param {Color} eyeColor 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eyeColorShare(eyeColor: Color, options?: RawAxiosRequestConfig): AxiosPromise<number> {
            return localVarFp.eyeColorShare(eyeColor, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary рассчитать сумму значений height для всех Person
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sumHeight(options?: RawAxiosRequestConfig): AxiosPromise<number> {
            return localVarFp.sumHeight(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OperationsApi - object-oriented interface
 */
export class OperationsApi extends BaseAPI {
    /**
     * 
     * @summary вывести количество людей с заданным цветом волос в пределах указанной локации
     * @param {Color} hairColor 
     * @param {number} locationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public countByHairColorAndLocation(hairColor: Color, locationId: number, options?: RawAxiosRequestConfig) {
        return OperationsApiFp(this.configuration).countByHairColorAndLocation(hairColor, locationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary вернуть количество Person с заданным height
     * @param {number} height 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public countByHeight(height: number, options?: RawAxiosRequestConfig) {
        return OperationsApiFp(this.configuration).countByHeight(height, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary удалить один объект с заданной национальностью
     * @param {Country} nationality 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteByNationality(nationality: Country, options?: RawAxiosRequestConfig) {
        return OperationsApiFp(this.configuration).deleteByNationality(nationality, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary вывести долю людей с заданным цветом глаз в процентах
     * @param {Color} eyeColor 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public eyeColorShare(eyeColor: Color, options?: RawAxiosRequestConfig) {
        return OperationsApiFp(this.configuration).eyeColorShare(eyeColor, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary рассчитать сумму значений height для всех Person
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sumHeight(options?: RawAxiosRequestConfig) {
        return OperationsApiFp(this.configuration).sumHeight(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PersonsApi - axios parameter creator
 */
export const PersonsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary создать новый объект Person
         * @param {PersonRequest} personRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPerson: async (personRequest: PersonRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('createPerson', 'personRequest', personRequest)
            const localVarPath = `/persons`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(personRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary удалить Person
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePerson: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('deletePerson', 'id', id)
            const localVarPath = `/persons/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary получить Person по id
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPersonById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('getPersonById', 'id', id)
            const localVarPath = `/persons/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary поиск и фильтрация Person
         * @param {SearchRequest} searchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchPersons: async (searchRequest: SearchRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('searchPersons', 'searchRequest', searchRequest)
            const localVarPath = `/persons/search`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary обновить Person
         * @param {number} id идентификатор ресурса
         * @param {PersonRequest} personRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePerson: async (id: number, personRequest: PersonRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExists('updatePerson', 'id', id)
            assertParamExists('updatePerson', 'personRequest', personRequest)
            const localVarPath = `/persons/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(personRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PersonsApi - functional programming interface
 */
export const PersonsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PersonsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary создать новый объект Person
         * @param {PersonRequest} personRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPerson(personRequest: PersonRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPerson(personRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonsApi.createPerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary удалить Person
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePerson(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePerson(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonsApi.deletePerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary получить Person по id
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPersonById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPersonById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonsApi.getPersonById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary поиск и фильтрация Person
         * @param {SearchRequest} searchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchPersons(searchRequest: SearchRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagePerson>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchPersons(searchRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonsApi.searchPersons']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary обновить Person
         * @param {number} id идентификатор ресурса
         * @param {PersonRequest} personRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePerson(id: number, personRequest: PersonRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePerson(id, personRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonsApi.updatePerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PersonsApi - factory interface
 */
export const PersonsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PersonsApiFp(configuration)
    return {
        /**
         * 
         * @summary создать новый объект Person
         * @param {PersonRequest} personRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPerson(personRequest: PersonRequest, options?: RawAxiosRequestConfig): AxiosPromise<PersonResponse> {
            return localVarFp.createPerson(personRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary удалить Person
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePerson(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletePerson(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary получить Person по id
         * @param {number} id идентификатор ресурса
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPersonById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<PersonResponse> {
            return localVarFp.getPersonById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary поиск и фильтрация Person
         * @param {SearchRequest} searchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchPersons(searchRequest: SearchRequest, options?: RawAxiosRequestConfig): AxiosPromise<PagePerson> {
            return localVarFp.searchPersons(searchRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary обновить Person
         * @param {number} id идентификатор ресурса
         * @param {PersonRequest} personRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePerson(id: number, personRequest: PersonRequest, options?: RawAxiosRequestConfig): AxiosPromise<PersonResponse> {
            return localVarFp.updatePerson(id, personRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PersonsApi - object-oriented interface
 */
export class PersonsApi extends BaseAPI {
    /**
     * 
     * @summary создать новый объект Person
     * @param {PersonRequest} personRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createPerson(personRequest: PersonRequest, options?: RawAxiosRequestConfig) {
        return PersonsApiFp(this.configuration).createPerson(personRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary удалить Person
     * @param {number} id идентификатор ресурса
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletePerson(id: number, options?: RawAxiosRequestConfig) {
        return PersonsApiFp(this.configuration).deletePerson(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary получить Person по id
     * @param {number} id идентификатор ресурса
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPersonById(id: number, options?: RawAxiosRequestConfig) {
        return PersonsApiFp(this.configuration).getPersonById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary поиск и фильтрация Person
     * @param {SearchRequest} searchRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchPersons(searchRequest: SearchRequest, options?: RawAxiosRequestConfig) {
        return PersonsApiFp(this.configuration).searchPersons(searchRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary обновить Person
     * @param {number} id идентификатор ресурса
     * @param {PersonRequest} personRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updatePerson(id: number, personRequest: PersonRequest, options?: RawAxiosRequestConfig) {
        return PersonsApiFp(this.configuration).updatePerson(id, personRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



