/* tslint:disable */
/* eslint-disable */
/**
 * Person Management API
 * API для управления объектами Person. Backend на Jakarta EE + JPA (EclipseLink).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

